font_family      Mononoki Nerd Font Mono
italic_font      auto
bold_font        auto
bold_italic_font auto

# Font size
font_size        16.0

# Padding

# Color theme
include themes/catppuccin-frappe.conf
